### ISSUE TITLE
CUDA kernel failed : no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by CNJianLiu** [HalfSummer11/CAPTRA#10]
Hi, thank you for releasing such a wonderful job! But I got an error: "CUDA kernel failed : no kernel image is available for execution on the device" when both testing and training, I have checked my environment and did not find any problem.
Testing:
![testing](https://user-images.githubusercontent.com/80870150/145786649-7fee29b5-501f-43f1-88d9-3529b47d920f.PNG)
Traing:
![training](https://user-images.githubusercontent.com/80870150/145786672-bad1f248-9eef-4069-a692-5e0aea50e818.PNG)
My environment settings:
![1](https://user-images.githubusercontent.com/80870150/145786842-c2dbe80b-199f-49ab-a924-fa30dab6addb.PNG)
Terminal checking:
![2](https://user-images.githubusercontent.com/80870150/145786918-0e01d6a1-5fb8-4519-b282-ed3761ffc0f6.PNG)

**Comment by ray8828** [comment]
Hi, how did you solve this issue? Thanks!

**Comment by ray8828** [comment]
Oops, Seems like our slurm cluster issue

**Comment by CNJianLiu** [comment]
> Oops, Seems like our slurm cluster issue

I am because of the environment error.
BTW: have you used your training model for testing? Does the training model similar to the authors' pre-trained model? There is still an issue [https://github.com/HalfSummer11/CAPTRA/issues/11](url)

**Comment by CNJianLiu** [comment]
> Oops, Seems like our slurm cluster issue

I am because of the environment error.
BTW: have you used your training model for testing? Does the training model similar to the authors' pre-trained model? There is still an issue #11

**Comment by njfugit** [comment]
译文

Hello, I want to know how to modify your environment. I also use 3090 graphics card and have the same problem. The CUDA and Torch versions I used may have issues.

**Comment by CNJianLiu** [comment]
> 译文
> 
> Hello, I want to know how to modify your environment. I also use 3090 graphics card and have the same problem. The CUDA and Torch versions I used may have issues.


Hi, I reinstalled the environment and installed 'cuda11.0.3 & pytorch1.7.0' to solve this problem.

**Comment by njfugit** [comment]
OK, I tried cuda11.0 and torch1.7.0. But it is not solved. I can solve it with cuda11.1 and torch1.9.0-------- 原始邮件 --------发件人： Jian Liu ***@***.***>日期： 2022年3月2日周三 10:32收件人： HalfSummer11/CAPTRA ***@***.***>抄送： njfugit ***@***.***>, Comment ***@***.***>主    题： Re: [HalfSummer11/CAPTRA] CUDA kernel failed : no kernel image is available for execution on the device (Issue #10)



译文

Hello, I want to know how to modify your environment. I also use 3090 graphics card and have the same problem. The CUDA and Torch versions I used may have issues.



Hi, I reinstalled the environment and installed 'cuda11.0.3 & pytorch1.7.0' to solve this problem.
