### ISSUE TITLE
What's the purpos of the perturbed_part

### ISSUE THREAD

**Issue by ray8828** [HalfSummer11/CAPTRA#13]
https://github.com/HalfSummer11/CAPTRA/blob/1eab3fa7a0307e4f658e4401c5ca75436838c8e8/network/models/model.py#L414

Hi, thanks for sharing the code. 

Seems that the `perturbed_part` is never used later, I'm curious what this poses with noise for? Thanks

**Comment by HalfSummer11** [comment]
Hi, thanks for pointing out this piece of redundant code. This pose was used for debugging purposes where we tried to keep part of the pose (e.g. scale) a perturbed version of ground-truth while taking the rest of the pose from the previous frame's prediction. Sorry that we forgot to clean it in the release.
