### ISSUE TITLE
A typo in func eval_single_part_iou() ?

### ISSUE THREAD

**Issue by Bear-kai** [HalfSummer11/CAPTRA#18]
In pose_utils/bbox_utils.py, Line 175 . [link](https://github.com/HalfSummer11/CAPTRA/blob/main/pose_utils/bbox_utils.py#L175)
The "**pred_pose['rotation']**" should be "**gt_pose['rotation']**" ?!

`cur_pose['rotation'] = torch.matmul(pred_pose['rotation'], y_rotation_matrix(2 * np.pi * i / float(n)).reshape(1, 1, 3, 3))
`

**Comment by HalfSummer11** [comment]
Thanks for catching the mistake! We've corrected the typo.
